# Generated by Django 6.0.3 on 2026-05-11 11:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('evenements', '0001_initial'),
        ('parametres', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_facture', models.DateField(verbose_name='Date de facture')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_finalisation', models.DateTimeField(blank=True, null=True, verbose_name='Date de finalisation')),
                ('date_arrivee', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée")),
                ('date_depart', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('type_facture', models.CharField(choices=[('proforma', 'Proforma'), ('definitive', 'Définitive')], default='proforma', max_length=20, verbose_name='Type de facture')),
                ('statut', models.CharField(choices=[('proforma', 'Proforma'), ('definitive', 'En réglement'), ('envoyee', 'Envoyée'), ('partiel', 'Partiellement soldé'), ('payee', 'Soldé'), ('annulee', 'Annulée'), ('impayee', 'Impayée')], default='proforma', max_length=20, verbose_name='Statut')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('est_archive', models.BooleanField(default=False, verbose_name='Archivée')),
                ('notes', models.TextField(blank=True, default='Prestation: Atelier du x mois année /x pax x jours')),
                ('conditions', models.TextField(blank=True, default="Bon de commande à la confirmation de la commande, versement des 50% avant l'atelier et les 50% restant à la fin de l'atelier", verbose_name='Conditions de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant de la commission')),
                ('taux_commission', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de commission (%)')),
                ('commissionnaire', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du commissionnaire')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='clients.client', verbose_name='Client')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='parametres.entreprise')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='evenements.evenement', verbose_name='Événement lié')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire HT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='factures.facture', verbose_name='Facture')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_facture', to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
    ]
