# Generated by Django 6.0.3 on 2026-04-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='conditions',
            field=models.TextField(blank=True, default="Bon de commande à la confirmation de la commande, versement des 50% avant l'atelier et les 50% restant à la fin de l'atelier", verbose_name='Conditions de paiement'),
        ),
    ]
