# Generated by Django 6.0.3 on 2026-04-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_alter_facture_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='notes',
            field=models.TextField(blank=True, default='Prestation: Atelier du x mois année /x pax x jours'),
        ),
    ]
