# Generated by Django 6.0.3 on 2026-04-24 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
        ('factures', '0003_alter_facture_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='evenements.evenement', verbose_name='Événement lié'),
        ),
    ]
