# Generated by Django 6.0.3 on 2026-04-25 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0002_remove_evenement_type_event_remove_evenement_adresse_and_more'),
        ('factures', '0004_facture_evenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='evenements.evenement', verbose_name='Événement lié'),
        ),
    ]
