# Generated by Django 6.0.3 on 2026-04-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_alter_facture_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant de la commission'),
        ),
        migrations.AddField(
            model_name='facture',
            name='commissionnaire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du commissionnaire'),
        ),
        migrations.AddField(
            model_name='facture',
            name='taux_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de commission (%)'),
        ),
    ]
