# Generated by Django 6.0.3 on 2026-04-11 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Identifiant unique')),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprises_propriete', to=settings.AUTH_USER_MODEL)),
                ('utilisateurs', models.ManyToManyField(blank=True, related_name='entreprises_acces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='ParametresEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unique', models.BooleanField(blank=True, default=True, editable=False, null=True)),
                ('nom_entreprise', models.CharField(default='Mon Entreprise', max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='entreprises/images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='entreprises/images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='entreprises/images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='entreprises/images/')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='France', max_length=100)),
                ('siret', models.CharField(blank=True, max_length=14)),
                ('tva_intra', models.CharField(blank=True, max_length=20)),
                ('capital_social', models.CharField(blank=True, max_length=50)),
                ('forme_juridique', models.CharField(blank=True, max_length=100)),
                ('rcs', models.CharField(blank=True, max_length=50)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('banque', models.CharField(blank=True, max_length=100)),
                ('mentions_legales', models.TextField(blank=True)),
                ('conditions_paiement', models.TextField(blank=True, default='Paiement à réception de facture')),
                ('pied_page_facture', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entreprise', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='parametres.entreprise')),
            ],
            options={
                'verbose_name': "Paramètres de l'entreprise",
                'verbose_name_plural': "Paramètres de l'entreprise",
            },
        ),
        migrations.CreateModel(
            name='ParametresFacturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unique', models.BooleanField(blank=True, default=True, editable=False, null=True)),
                ('prefixe_facture', models.CharField(default='F', max_length=10)),
                ('annee_dans_numero', models.BooleanField(default=True)),
                ('separateur', models.CharField(default='-', max_length=5)),
                ('prochain_numero', models.IntegerField(default=1)),
                ('delai_paiement_jours', models.IntegerField(default=30)),
                ('tva_par_defaut', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('envoyer_email_auto', models.BooleanField(default=False)),
                ('rappel_paiement_auto', models.BooleanField(default=False)),
                ('jours_avant_relance', models.IntegerField(default=7)),
                ('devise', models.CharField(choices=[('EUR', 'Euro €'), ('USD', 'Dollar $'), ('GBP', 'Livre £'), ('XOF', 'Franc CFA')], default='EUR', max_length=3)),
                ('entreprise', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametres_facturation', to='parametres.entreprise')),
            ],
            options={
                'verbose_name': 'Paramètres de facturation',
                'verbose_name_plural': 'Paramètres de facturation',
            },
        ),
    ]
