# Generated by Django 6.0.3 on 2026-04-24 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_personne_ressource'),
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('couleur', models.CharField(default='#0d6efd', max_length=20, verbose_name='Couleur (HTML)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_evenements', to='parametres.entreprise')),
            ],
            options={
                'verbose_name': "Type d'événement",
                'verbose_name_plural': "Types d'événements",
                'ordering': ['nom'],
                'unique_together': {('nom', 'entreprise')},
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'événement")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('lieu', models.CharField(blank=True, max_length=300, verbose_name='Lieu')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('nombre_personnes', models.IntegerField(default=0, verbose_name='Nombre de personnes')),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Budget prévu')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='clients.client', verbose_name='Client')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='parametres.entreprise')),
                ('type_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='evenements.typeevenement', verbose_name="Type d'événement")),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
    ]
