# Generated by Django 6.0.3 on 2026-05-11 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Mariage', 'Mariage'), ('Séminaire', 'Séminaire'), ('Conférence', 'Conférence'), ('Anniversaire', 'Anniversaire'), ('Gala', 'Gala'), ('Team Building', 'Team Building'), ('Dîner', 'Dîner'), ('Lunch', 'Lunch'), ('Cocktail', 'Cocktail'), ('Réunion', 'Réunion'), ('Formation', 'Formation'), ('Hebergement', 'Hébergement'), ('Autre', 'Autre')], default='Autre', max_length=200, verbose_name="Nom de l'événement")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_arrivee', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée")),
                ('date_depart', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('lieu', models.CharField(blank=True, max_length=300, verbose_name='Lieu')),
                ('nombre_personnes', models.IntegerField(default=0, verbose_name='Nombre de personnes')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='clients.client', verbose_name='Client')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='parametres.parametresentreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
    ]
