# Generated by Django 6.0.3 on 2026-04-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='type_event',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='budget_prevu',
        ),
        migrations.DeleteModel(
            name='TypeEvenement',
        ),
    ]
