# Generated by Django 6.0.3 on 2026-04-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_adresse_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='personne_ressource',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Personne ressource'),
        ),
    ]
